Carbon:
  IncludeAssets:
    LoadJSforCSSAsynchron: true
    GoogleFonts: "Mulish:wght@300;400;800&display=swap"
    Packages:
      'Abte.Site':
        Package: 'Abte.Site'
        General:
          Head: 
            # - //use.typekit.net/bev6plj.css
            - Stwz.css
          Body: 
            - Stwz.js[defer]
        Backend:
          Head:
            # - Backend.css
            # - Backend.js[defer]
        Live:

      "Sitegeist.Lazybones":
        Package: Sitegeist.Lazybones
        Path:
          File:
            JS: 'Public/JavaScript'
        General:
          Body:
            - lazysizes.min.js
