Neos:
  Neos:
    userInterface:
      defaultLanguage: en
      translation:
        autoInclude:
          Abte.Site:
            - Main
            - 'NodeTypes/*'
  Flow:
    i18n:
      defaultLocale: de
  ContentRepository:
    contentDimensions:
      language:
        label: Languages
        icon: icon-language
        # The default dimension that is applied when creating nodes without specifying a dimension
        default: de
        # The default preset to use if no URI segment was given when resolving languages in the router
        defaultPreset: de
        presets:
          de:
            label: DE
            values:
              - de
            uriSegment: 'de'
          fr:
            label: FR
            values:
              - fr
              - de
            uriSegment: 'fr'
          en:
            label: EN
            values:
              - en
              - de
            uriSegment: 'en'