Carbon:
  IncludeAssets:
    LoadJSforCSSAsynchron: true
    GoogleFonts: "Mulish:300,400,800&display=swap[async]"
    Packages:
      'Abte.Site':
        Package: 'Abte.Site'
        General:
          Head: 
            - Stwz.css
            - LineAnimation.css
          Body: 
            - Stwz.js[defer]
        Backend:
          Head:
            # - Backend.css
            # - Backend.js[defer]