'Abte.Site:Content.ProductCard':
  superTypes:
    'Neos.Neos:Content': true
    'Abte.Site:Mixin.BgColor': true
    'Abte.Site:Mixin.IsHero': true
  ui:
    label: ProductCard
    icon: cart-plus
    position: 7
    inlineEditable: true
  properties:
    title:
      options:
        preset: 'text.title'
    subTitle:
      options:
        preset: 'text.title'
    description:
      options:
        preset: 'text.free'
    price:
      options:
        preset: 'text.plain'
    discount:
      options:
        preset: 'text.plain'        