'Abte.Site:Content.Products':
  superTypes:
    'Neos.Neos:Content': true
    'Neos.Neos:ContentCollection': true
  label: "${ q(node).property('discount') && node.context.inBackend ? '<span class=\"hidden\">🔥 </span>' + q(node).property('discount') + '%' : q(node).property('title') }"
  ui:
    label: Produkte
    position: 8
    inlineEditable: true
    group: general
    icon: shopping-basket
  constraints:
    nodeTypes:
      '*': false
      'Abte.Site:Content.ProductCard': true
  properties:
    'title':
      options:
        preset: 'text.title'
    'discount':
      options:
        preset: 'text.plain'
      ui:
        label: 'Rabatt (%)'
        inspector:
          group: 'general'
    'group':
      ui:
        label: 'Gruppe'
        inspector:
          group: 'general'
      options:
        preset: 'text.title'
  options:
    template:
      childNodes:
        multipleAccordionNodes:
          type: 'Abte.Site:Content.ProductCard'
          properties:
            title: '${"" + item + ""}'
          withItems:
            - 'Produkt 1'
            - 'Produkt 2'
            - 'Produkt 3'