'Abte.Site:Content.ProductCard':
  superTypes:
    'Neos.Neos:Content': true
    'Abte.Site:Mixin.BgColor': true
    'Abte.Site:Mixin.IsHero': true
    'Abte.Site:Mixin.ShowSpeed': true
  ui:
    label: ProductCard
    icon: cart-plus
    position: 7
    inlineEditable: true
  properties:
    title:
      options:
        preset: 'text.title'
    subTitle:
      options:
        preset: 'text.title'
    description:
      options:
        preset: 'text.free'
    price:
      options:
        preset: 'text.inspector'
      ui:
        label: 'Prouktpreis'
    discount:
      options:
        preset: 'text.plain'

    productGUID:
      options:
        preset: 'text.inspector'
      ui:
        label: GUID (Shop)
    productIV:
      options:
        preset: 'text.inspector'
      ui:
        label: IV (Shop)
