'Abte.Site:Document.Products':
  superTypes:
    'Abte.Site:Document.AbstractPage': true
    'Abte.Site:Mixin.Image': true
    'Abte.Site:Mixin.TeaserText': true
    'Abte.Site:Constraint.Document.Restricted': true
  ui:
    label: i18n
    icon: archive
    position: 700
  constraints:
    nodeTypes:
      '*': false
      'Abte.Site:Document.Category': true
      'Abte.Site:Document.Service': true
      'Abte.Site:Document.Product': true
  childNodes:
    aside:
      type: 'Neos.Neos:ContentCollection'
