'Abte.Site:Document.Product':
  superTypes:
    'Abte.Site:Document.AbstractPage': true
    'Abte.Site:Mixin.Image': true
    'Abte.Site:Mixin.Icons': true
    'Stwz.Flickity:Include': true
    'Abte.Site:Mixin.TeaserText': true
    'Abte.Site:Mixin.Illustration': true
    'Abte.Site:Constraint.Document.Restricted': true
    'Abte.Site:Mixin.Searchable.SiteSearch': true
  ui:
    label: i18n
    icon: box-open
    position: 700
    inspector:
      groups:
        product:
          label: Product
          position: 9
          icon: cube
          collapsed: true
        style:
          position: 10
          icon: palette
          collapsed: true
        document:
          position: 5
  constraints:
    nodeTypes:
      '*': false
  properties:
    'accordion_open':
      type: string
      defaultValue: ''
      position: 1
      ui:
        label: Shop-Element öffnen (Nr.)
        reloadPageIfChanged: true
        inspector:
          group: document