'Abte.Site:Document.Product':
  superTypes:
    'Abte.Site:Document.AbstractPage': true
    'Abte.Site:Mixin.Image': true
    'Abte.Site:Mixin.Icons': true
    'Abte.Site:Constraint.Document.Restricted': true
    'Abte.Site:Mixin.Searchable.SiteSearch': true
  ui:
    label: i18n
    icon: box-open
    position: 700
    inspector:
      groups:
        product:
          label: Product
          position: 9
          icon: cube
          collapsed: true
        style:
          position: 10
          icon: palette
          collapsed: true
        document:
          position: 5
  constraints:
    nodeTypes:
      '*': false
  childNodes:
    video:
      type: 'Neos.Neos:ContentCollection'
      position: 'after main'
  properties:
    categories:
      type: references
      ui:
        label: 'Kategorien'
        reloadIfChanged: TRUE
        inspector:
          group: 'document'
          position: 20
          editorOptions:
            nodeTypes: ['Abte.Site:Document.Category']
            # startingPoint: "ClientEval:node.properties._path.replace(/(.+)(\\/.+)/, '$1')"
            # startingPoint: /Kategorien