'Abte.Site:Document.Product':
  superTypes:
    'Abte.Site:Document.AbstractPage': true
    'Abte.Site:Mixin.Image': true
    'Selfix.Flickity:Include': true
    'Abte.Site:Constraint.Document.Restricted': true
    'Abte.Site:Mixin.Searchable.SiteSearch': true
    'Abte.Site:Mixin.Product.Price': true
    'Abte.Site:Mixin.Product.Identifiers': true
    'Abte.Site:Mixin.Product.CommonFeatures': true
    'Abte.Site:Mixin.Product.Label': true
    'Abte.Site:Mixin.Product.Farbband': true
    'Abte.Site:Mixin.Product.Rolls': true
    'Abte.Site:Mixin.Product.Packaging': true
    'Abte.Site:Mixin.Product.Logistics': true
    'Abte.Site:Mixin.Product.Ink': true
    'Abte.Site:Mixin.Product.Dimensions': true
    'Abte.Site:Mixin.Product.Electricity': true
    'Abte.Site:Mixin.Product.Connectivity': true
    'Abte.Site:Mixin.Product.SalesFeatures': true
    'Abte.Site:Mixin.Product.PrinterFeatures': true
    'Abte.Site:Mixin.Product.DeviceFeatures': true
  ui:
    label: i18n
    icon: box-open
    position: 700
    inspector:
      groups:
        product:
          label: Product
          position: 9
          icon: cube
          collapsed: true
        style:
          position: 10
          icon: palette
          collapsed: true
        document:
          position: 5
  constraints:
    nodeTypes:
      '*': false
  childNodes:
    video:
      type: 'Neos.Neos:ContentCollection'
      position: 'after main'
  properties:
    categories:
      type: references
      ui:
        label: 'Kategorien'
        reloadIfChanged: TRUE
        inspector:
          group: 'document'
          position: 20
          editorOptions:
            nodeTypes: ['Abte.Site:Document.Category']
            # startingPoint: "ClientEval:node.properties._path.replace(/(.+)(\\/.+)/, '$1')"
            # startingPoint: /Kategorien
    # __label:
    #   options:
    #     preset: 'text.plain'
    productVisiblity:
      options:
        preset: 'boolean'
      defaultValue: 'true'
      ui:
        label: 'Product is visible'
        inspector:
          group: style
          editorOptions:
            disabled: true
    productIsSynced:
      options:
        preset: boolean
      defaultValue: false
      ui:
        label: Is Synced
        inspector:
          group: product
          position: 0
          editorOptions:
            disabled: true
    productChampion:
      options:
        preset: 'boolean'
      ui:
        label: 'Product is Champion'
        inspector:
          group: product
          editorOptions:
            disabled: true
    productDescription:
      options:
        preset: 'text.free'
      ui:
        label: Description
        inspector:
          group: product
          editorOptions:
            disabled: true
    productDescriptionShort:
      options:
        preset: 'text.free'
      ui:
        label: Description Short
        inspector:
          group: product
          editorOptions:
            disabled: true
    productFunction:
      options:
        preset: 'text.free'
      ui:
        label: Funktion
        inspector:
          group: product
          editorOptions:
            disabled: true
    productMinOutlet:
      options:
        preset: 'text.free'
      ui:
        label: Min. Durchlass
        inspector:
          group: product
          editorOptions:
            disabled: true
    productMaxOutlet:
      options:
        preset: 'text.free'
      ui:
        label: Max. Durchlass
        inspector:
          group: product
          editorOptions:
            disabled: true
    productUi:
      options:
        preset: 'text.free'
      ui:
        label: Benutzeroberfläche
        inspector:
          group: product
          editorOptions:
            disabled: true
    productMedia:
      options:
        preset: 'text.free'
      ui:
        label: Medium (Etikettiergut)
        inspector:
          group: product
          editorOptions:
            disabled: true
    productMaterial:
      options:
        preset: 'text.plain'
      ui:
        label: Material
        inspector:
          group: product
          editorOptions:
            disabled: true
    productGummierung:
      options:
        preset: 'text.plain'
      ui:
        label: Gumming
        inspector:
          group: product
          editorOptions:
            disabled: true
    productAusfuehrung:
      options:
        preset: 'text.plain'
      ui:
        label: Ausführung
        inspector:
          group: product
          editorOptions:
            disabled: true
    productImageUrl:
      options:
        preset: 'text.plain'
      ui:
        label: 'Image Url (WP)'
        inspector:
          group: image
    'downloads':
      options:
        preset: 'image.assets'
      ui:
        label: 'Datenblätter (PDF)'
        inspector:
          group: downloads
    'downloadPic':
      options:
        preset: 'image.tvAsset'
      ui:
        label: 'Placeholder for Download Image'
        inspector:
          group: downloads
    # can this below be moved to own or device mixin? For now just appearing for printers
    productManufacturer:
      options:
        preset: 'text.plain'
      ui:
        label: Manufacturer
        inspector:
          group: product
          editorOptions:
            disabled: true   
    productCompatability:
      options:
        preset: 'text.plain'
      ui:
        label: Compatability
        inspector:
          group: product
          editorOptions:
            disabled: true   
    productCompatabilityGroup:
      options:
        preset: 'text.plain'
      ui:
        label: Compatability Group
        inspector:
          group: product
          editorOptions:
            disabled: true
    productMaxMediaThickness:
      options:
        preset: 'text.plain'
      ui:
        label: Max Media Thickness
        inspector:
          group: product
          editorOptions:
            disabled: true
    productMinPrintLength:
      options:
        preset: 'text.plain'
      ui:
        label: Min Print Length
        inspector:
          group: product
          editorOptions:
            disabled: true  
    productMaxPrintLength:
      options:
        preset: 'text.plain'
      ui:
        label: Max Print Length
        inspector:
          group: product
          editorOptions:
            disabled: true  
    productMinPrintWidth:
      options:
        preset: 'text.plain'
      ui:
        label: Min Print Width
        inspector:
          group: product
          editorOptions:
            disabled: true   
    productMaxPrintWidth:
      options:
        preset: 'text.plain'
      ui:
        label: Max Print Width
        inspector:
          group: product
          editorOptions:
            disabled: true  