'Abte.Site:Document.Product':
  superTypes:
    'Abte.Site:Document.AbstractPage': true
    'Abte.Site:Mixin.Image': true
    'Abte.Site:Mixin.Icons': true
    'Abte.Site:Constraint.Document.Restricted': true
    'Abte.Site:Mixin.Searchable.SiteSearch': true
  ui:
    label: i18n
    icon: box-open
    position: 700
    inspector:
      groups:
        product:
          label: Product
          position: 9
          icon: cube
          collapsed: true
        style:
          position: 10
          icon: palette
          collapsed: true
        document:
          position: 5
  constraints:
    nodeTypes:
      '*': false
  childNodes:
    video:
      type: 'Neos.Neos:ContentCollection'
      position: 'after main'
  properties:
    'accordion_open':
      options:
        preset: 'text.inspector'
      ui:
        label: 'Welches Accordion öffnen?'
        inspector:
          group: document