'Abte.Site:Document.Services':
  superTypes:
    'Abte.Site:Document.AbstractPage': true
    'Abte.Site:Mixin.Image': true
    'Abte.Site:Mixin.TeaserText': true
    'Abte.Site:Constraint.Document.Restricted': true
    'Selfix.Flickity:Include': true
  ui:
    label: i18n
    icon: hands
    position: 700
  childNodes:
    aside:
      type: 'Neos.Neos:ContentCollection'
  constraints:
    nodeTypes:
      '*': false
      'Abte.Site:Document.Service': true