'Abte.Site:Mixin.Product.Connectivity':
  ui:
    inspector:
      groups:
        connectivity:
          label: Connectivity
          position: 15
          icon: plug
          collapsed: true
  properties:
    # productInputs:
    #   options:
    #     preset: 'text.plain'
    #   ui:
    #     label: Product Output
    #     inspector:
    #       group: product
    #       editorOptions:
    #         disabled: true
    # productOutputs:
    #   options:
    #     preset: 'text.plain'
    #   ui:
    #     label: Product Output
    #     inspector:
    #       group: product
    #       editorOptions:
    #         disabled: true