'Abte.Site:Mixin.Product.Price':
  ui:
    inspector:
      groups:
        price:
          label: Preise
          position: 18
          icon: dollar-sign
          collapsed: true
  properties:
    productPrice:
      options:
        preset: 'text.plain'
      ui:
        label: Product Price
        inspector:
          group: product
          editorOptions:
            disabled: false
    productPriceDiscount:
      options:
        preset: 'text.plain'
      ui:
        label: Discount
        inspector:
          group: product
          editorOptions:
            disabled: false