'Abte.Site:Mixin.Product.Ink':
  ui:
    inspector:
      groups:
        ink:
          label: Ink
          position: 40
          icon: tint
          collapsed: true
  properties:
    inkQuality:
      options:
        preset: 'text.plain'
      ui:
        label: Ink Quality
        inspector:
          group: ink
          editorOptions:
            disabled: true
    inkFill:
      options:
        preset: 'text.plain'
      ui:
        label: Ink Fill
        inspector:
          group: ink
          editorOptions:
            disabled: true