'Abte.Site:Mixin.Product.Dimensions':
  ui:
    inspector:
      groups:
        dimensions:
          label: Dimensionen
          position: 12
          icon: ruler
          collapsed: true
  properties:
    productWeight:
      options:
        preset: 'text.plain'
      ui:
        label: Weight (kg)
        inspector:
          group: dimensions
          editorOptions:
            disabled: true
    productWidth:
      options:
        preset: 'text.plain'
      ui:
        label: Width (cm)
        inspector:
          group: dimensions
          editorOptions:
            disabled: true
    productHeight:
      options:
        preset: 'text.plain'
      ui:
        label: Height (cm)
        inspector:
          group: dimensions
          editorOptions:
            disabled: true
    productLength:
      options:
        preset: 'text.plain'
      ui:
        label: Depth (cm)
        inspector:
          group: dimensions
          editorOptions:
            disabled: true
    productDiameter:
      options:
        preset: 'text.plain'
      ui:
        label: Diameter (cm)
        inspector:
          group: dimensions
          editorOptions:
            disabled: true
    productForm:
      options:
        preset: 'text.plain'
      ui:
        label: Shape
        inspector:
          group: dimensions
          editorOptions:
            disabled: true
    # SEE mixin Rolls
    # productCoreWidth:
    #   options:
    #     preset: 'text.plain'
    #   ui:
    #     label: Produkt Kernbreite
    #     inspector:
    #       group: dimensions
    #       editorOptions:
    #         disabled: true
    # productCoreDiameter:
    #   options:
    #     preset: 'text.plain'
    #   ui:
    #     label: Produkt Kerndurchmesser
    #     inspector:
    #       group: dimensions
    #       editorOptions:
    #         disabled: true                        