'Abte.Site:Mixin.Product.CommonFeatures':
  properties:
    descriptionLong:
      options:
        preset: 'text.plain'
      ui:
        label: Description (Content)
        inspector:
          group: product
          editorOptions:
            disabled: true