'Abte.Site:Mixin.Product.PrinterFeatures':
  ui:
    inspector:
      groups:
        printer:
          label: Drucker
          position: 60
          icon: print
          collapsed: true
  properties:
    printerType:
      options:
        preset: 'text.plain'
      ui:
        label: Printer Type
        inspector:
          group: printer
          editorOptions:
            disabled: true
    printerHead:
      options:
        preset: 'text.plain'
      ui:
        label: Printer Head Type
        inspector:
          group: printer
          editorOptions:
            disabled: true
    printerPrintProcess:
      options:
        preset: 'text.plain'
      ui:
        label: Print Process
        inspector:
          group: printer
          editorOptions:
            disabled: true
    printerMedia:
      options:
        preset: 'text.plain'
      ui:
        label: Printer Media
        inspector:
          group: printer
          editorOptions:
            disabled: true
    printerResolution:
      options:
        preset: 'text.plain'
      ui:
        label: DPI
        inspector:
          group: printer
          editorOptions:
            disabled: true
    printerCutter:
      options:
        preset: 'text.plain'
      ui:
        label: 'Cutter'
        inspector:
          group: printer
          editorOptions:
            disabled: true
    printerCardridges:
      options:
        preset: 'text.plain'
      ui:
        label: Cardridges
        inspector:
          group: printer
          editorOptions:
            disabled: true 
    printerPassthroughMin:
      options:
        preset: 'text.plain'
      ui:
        label: Min. Durchlass
        inspector:
          group: product
          editorOptions:
            disabled: true 
    printerPassthroughMax:
      options:
        preset: 'text.plain'
      ui:
        label: Max. Durchlass
        inspector:
          group: product
          editorOptions:
            disabled: true 
    printerSpeed:
      options:
        preset: 'text.plain'
      ui:
        label: Printing Speed
        inspector:
          group: product
          editorOptions:
            disabled: true 
