Carbon:
  IncludeAssets:
    LoadJSforCSSAsynchron: true
    Packages:
      'Stwz.AddressLookup':
        Package: 'Stwz.AddressLookup'
        General:
          Head: 
            - AddressLookup.css
          Body: 
            - AddressLookup.js