Carbon:
  IncludeAssets:
    LoadJSforCSSAsynchron: true
    Packages:
      'Stwz.Shop':
        Package: 'Stwz.Shop'
        General:
          Head: 
            - Shop.css
          Body:
            - Shop.js