Neos:
  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        host: 'localhost'
        port: '1025'
        encryption: null
        username: null
        password: null
        localDomain: '127.0.0.1'
